### PR TITLE
Add icon for elisp

### PR DESCRIPTION
**Pull request by thefossenjoyer**

### CODE REVIEW

**Comment by Zulu-Inuoe** [comment]
I don't know that this logo makes sense when we already use the official GNU Emacs one.
Where's this from?

**Comment by thefossenjoyer** [comment]
I just did a google search. :man_shrugging:

**Comment by thefossenjoyer** [comment]
Or we could reuse the lisp icon. :man_shrugging:

**Comment by Zulu-Inuoe** [comment]
But what's wrong with the official icon we use now?

emacs icon

**Comment by thefossenjoyer** [comment]
Pardon me, I only noticed it recently while playing with config. I thought there wasn't an icon for it.

**Comment by Mstrodl** [comment]
I'm going to close this for now unless we have some confirmation this is an official icon

Also, this should really be a transparent image, and only one of them

**Pull request closed without merging**
