### PR TITLE
Make buffer details format configurable

### PR DESCRIPTION
**Pull request by ve-nt**

### CODE REVIEW

**Comment by Zulu-Inuoe** [comment]
@ve-nt I like the idea, but how about providing a function the user can override, instead? This way they can include/exclude any information they like without being restricted to a string for `format`

**Comment by ve-nt** [comment]
That's a good idea, I'll take this PR in that direction. Thanks!

**Comment by ve-nt** [comment]
Okay, I have implemented the changes. It's now configured with a function and not a format string. For my original use case, which was just removing the word "Editing", configuring it is as lean as this:

```emacs-lisp
(setq elcord-buffer-details-format-function 'buffer-name)
```

**Comment by Zulu-Inuoe** [comment]
Hi @ve-nt thanks for looking at this, and sorry for the delay in pulling it in!

**Pull request merged**
