### PR TITLE
Idle status

### PR DESCRIPTION
**Pull request by chaoky**
https://github.com/Mstrodl/elcord/pull/34

### CODE REVIEW

**Comment by ninjaguppy** [comment]
Any updates on this? I'm using the daemon so according to Discord I am playing emacs 24/7

**Comment by Mstrodl** [comment]
It might be better to unset our activity entirely when idle... Sorry for dropping the ball on this!

**Comment by chaoky** [comment]
I don't understand why this got approved but never got merged :thinking:

**Comment by chaoky** [comment]
> It might be better to unset our activity entirely when idle... Sorry for dropping the ball on this!

that's also a good ideia, but why not have both options? most other apps display an idle status instead of just stopping

**Comment by Mstrodl** [comment]
> I don't understand why this got approved but never got merged thinking

I forgot!

**Review by Mstrodl — APPROVED** [review]

**Pull request merged**
