### PR TITLE
wsl support

### PR DESCRIPTION
**Pull request by chaoky**
Only tested with wsl2

### CODE REVIEW

**Comment by chaoky** [comment]
Hey, I'm not very confident in my emacs lisp, but It seems to be working.

**Comment by chaoky** [comment]
after reading more about socat and unix sockets, a better solution was pretty obvious. this branch was hard reset to not pollute the commits.

**Comment by chaoky** [comment]
I'm trying to replace `npiperelay` with `stdpipe.ps1` but only the first rpc response comes through and I have no idea why

**Comment by Mstrodl** [comment]
cc @Zulu-Inuoe ^

**Comment by Zulu-Inuoe** [comment]
Maybe it's to do with the PID? I don't know how wsl PID's work, but if Discord is running outside of wsl, emacs inside of it (or vice versa) then maybe Discord doesn't find the PID and considers it a bogus setup

**Comment by Mstrodl** [comment]
Good point actually, I know Discord does check the pid in order to track it (so that in the event your game crashes it will remove the presence)

**Comment by Zulu-Inuoe** [comment]
You can try giving the PID of the powershell process hosting stdpipe.ps1? Again, I'm not sure about the exact setup.

**Comment by chaoky** [comment]
I don't think that's the case, `(emacs-pid)` works fine with `npiperelay`

**Comment by chaoky** [comment]
under windows, the code bellow is returning "Hello" every time emacs sends a message,
under wsl, it's just returning "Hello" once,
so weird.

```c#
        var tasks = new Task<int>[1]
        {
            ReadFromStdinAsync(stdBuffer, 0, stdBuffer.Length)
        };

        while (true)
        {
            var doneIdx = Task.WaitAny(tasks);            
            Console.Write("Hello");
            tasks[doneIdx] = ReadFromStdinAsync(stdBuffer, 0, stdBuffer.Length);
        }
```

**Comment by chaoky** [comment]
`WaitAny()` is just waiting forever after the first loop

**Comment by chaoky** [comment]
the binary version works fine

**Pull request closed without merging**
